### ISSUE TITLE
Point Cloud Format

### ISSUE THREAD

**Issue by giladrefael** [cogsys-tuebingen/csapex_generic_obstacle_detection#2]
What point cloud format does the obstacle detector expects as input?
Obviously I should supply x,y,z fields as float, but how should I format the intensity data? I tried adding "r" or "intensity" as a uint8 but it doesn't seem to be working.
Thanks!

**Comment by betwo** [comment]
Hi @hendrix911, sorry for the late answer.

If you have intensity data, you should provide it as a float value, please see
http://docs.pointclouds.org/trunk/structpcl_1_1_point_x_y_z_i.html

To elaborate:
By default, the core detector is specifically instantiated for the following input point types:
```c++
template class ObstacleDetector3D<pcl::PointXYZ>;
template class ObstacleDetector3D<pcl::PointXYZI>;
template class ObstacleDetector3D<pcl::PointXYZRGB>;
```

Only the heat calculation needs more than XYZ information.
If you want to use one of the `heat_type`s {`HeatType::IROS16`, `HeatType::PATSY_OLD`}, then you need to provide the intensity, otherwise any other point type with XYZ should work.

Does that work for you?

Cheers
